FROM postgres:14.2

# Establish working directory on ubuntu virtual machine
WORKDIR /docker

# Make the build arguments available to Docker
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD

# Copy across files to virtual machine
COPY ./configure-locales.sh /docker/configure-locales.sh

# Update and configure container and database
RUN chmod -R 777 /docker && ./configure-locales.sh
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
