// File generated by WebFX (DO NOT EDIT MANUALLY)

module mongoose.base.client.presentationmodel {

    // Direct dependencies modules
    requires javafx.base;
    requires mongoose.base.shared.entities;

    // Exported packages
    exports mongoose.base.client.presentationmodel;

}