// File generated by WebFX (DO NOT EDIT MANUALLY)

module mongoose.ecommerce.client.businesslogic {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.base.client.aggregates;
    requires mongoose.base.client.entities;
    requires mongoose.base.shared.entities;
    requires mongoose.event.client.calendar;
    requires mongoose.hotel.shared.time;
    requires webfx.framework.shared.orm.entity;
    requires webfx.platform.shared.query;
    requires webfx.platform.shared.submit;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.ecommerce.client.businessdata.feesgroup;
    exports mongoose.ecommerce.client.businessdata.preselection;
    exports mongoose.ecommerce.client.businessdata.workingdocument;
    exports mongoose.ecommerce.client.businesslogic.feesgroup;
    exports mongoose.ecommerce.client.businesslogic.option;
    exports mongoose.ecommerce.client.businesslogic.pricing;
    exports mongoose.ecommerce.client.businesslogic.rules;
    exports mongoose.ecommerce.client.businesslogic.workingdocument;

}