// File generated by WebFX (DO NOT EDIT MANUALLY)

module mongoose.base.client.util {

    // Direct dependencies modules
    requires mongoose.base.client.entities;
    requires webfx.extras.type;
    requires webfx.framework.client.i18n;
    requires webfx.framework.shared.orm.entity;
    requires webfx.framework.shared.orm.expression;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.base.client.util.functions;
    exports mongoose.base.client.util.log;
    exports mongoose.base.client.util.routing;

}