// File generated by WebFX (DO NOT EDIT MANUALLY)

module mongoose.event.backoffice.activities.cloneevent.routing {

    // Direct dependencies modules
    requires mongoose.base.client.util;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.operation;
    requires webfx.platform.client.windowhistory;

    // Exported packages
    exports mongoose.event.backoffice.activities.cloneevent.routing;
    exports mongoose.event.backoffice.operations.routes.cloneevent;

}