package one.modality.ecommerce.payment.server.gateway.impl.anet;

import dev.webfx.platform.ast.AST;
import dev.webfx.platform.ast.ReadOnlyAstObject;
import dev.webfx.platform.async.Future;
import dev.webfx.platform.resource.Resource;
import dev.webfx.platform.util.collection.Collections;
import dev.webfx.platform.util.uuid.Uuid;
import net.authorize.Environment;
import net.authorize.api.contract.v1.*;
import net.authorize.api.controller.CreateTransactionController;
import one.modality.ecommerce.payment.PaymentStatus;
import one.modality.ecommerce.payment.SandboxCard;
import one.modality.ecommerce.payment.server.gateway.*;
import one.modality.ecommerce.payment.server.gateway.impl.util.RestApiOneTimeHtmlResponsesCache;

import java.math.BigDecimal;

import static one.modality.ecommerce.payment.server.gateway.impl.anet.AuthorizeRestApiJob.AUTHORIZE_PAYMENT_FORM_LOAD_ENDPOINT;

/**
 * @author Bruno Salmon
 */
public class AuthorizePaymentGateway implements PaymentGateway {

    static final String GATEWAY_NAME = "Authorize.net";

    private static final String HTML_TEMPLATE = Resource.getText(Resource.toUrl("modality-anet-payment-form-iframe.html", AuthorizePaymentGateway.class));

    private static final SandboxCard[] SANDBOX_CARDS = {
        new SandboxCard("Visa - Success", "4111 1111 1111 1111", null, "123", "46282"),
        new SandboxCard("Mastercard - Success", "5424 0000 0000 0015", null, "123", "46282"),
        new SandboxCard("Discover - Success", "6011 0000 0000 0012", null, "123", "46282"),
        new SandboxCard("American Express - Success", "3700 0000 0000 0002", null, "1234", "46282"),
        new SandboxCard("JCB - Success", "3088 0000 0000 0017", null, "123", "46282"),
        new SandboxCard("Dinners Club - Success", "3800 0000 0000 06", null, "123", "46282"),
        new SandboxCard("Wrong CVV", "4111 1111 1111 1111", null, "901", "46282"),
    };

    public AuthorizePaymentGateway() {
    }

    @Override
    public String getName() {
        return GATEWAY_NAME;
    }

    @Override
    public Future<GatewayInitiatePaymentResult> initiatePayment(GatewayInitiatePaymentArgument argument) {
        // Integrating the Authorize.net Hosted Payment Form inside the Modality page
        boolean live = argument.isLive();
        String apiLoginID = argument.getAccountParameter("apiLoginID");
        String clientKey = argument.getAccountParameter("clientKey");
        String acceptUIFormHeaderTxt = argument.getAccountParameter("acceptUIFormHeaderTxt", "");
        boolean seamless = false; //argument.isSeamlessIfSupported();

        String paymentFormContent = HTML_TEMPLATE
            .replace("${apiLoginID}", apiLoginID)
            .replace("${clientKey}", clientKey)
            .replace("${acceptUIFormHeaderTxt}", acceptUIFormHeaderTxt)
            ;

        SandboxCard[] sandboxCards = live ? null : SANDBOX_CARDS;
        if (seamless) {
            return Future.succeededFuture(GatewayInitiatePaymentResult.createEmbeddedContentInitiatePaymentResult(live, true, paymentFormContent, true, sandboxCards));
        } else { // In other cases, we embed the page in a WebView/iFrame that can be loaded through https (assuming this server is on https)
            String htmlCacheKey = Uuid.randomUuid();
            RestApiOneTimeHtmlResponsesCache.registerOneTimeHtmlResponse(htmlCacheKey, paymentFormContent);
            String url = AUTHORIZE_PAYMENT_FORM_LOAD_ENDPOINT.replace(":htmlCacheKey", htmlCacheKey);
            return Future.succeededFuture(GatewayInitiatePaymentResult.createEmbeddedUrlInitiatePaymentResult(live, false, url, true, sandboxCards));
        }
    }

    @Override
    public Future<GatewayCompletePaymentResult> completePayment(GatewayCompletePaymentArgument argument) {
        // Capturing argument parameters
        String apiLoginID = argument.getAccountParameter("apiLoginID");
        String apiTransactionKey = argument.getAccountParameter("apiTransactionKey");
        boolean live = argument.isLive();
        long amount = argument.getAmount();
        GatewayCustomer serverSideCustomer = argument.getCustomer();
        GatewayItem serverItem = argument.getItem();
        // Reading the payload generated by the script in modality-anet-payment-form-iframe.html
        ReadOnlyAstObject payload = AST.parseObject(argument.getPayload(), "json");
        String dataDescriptor      = payload.getString("anet_dataDescriptor");
        String dataValue           = payload.getString("anet_dataValue");
        String clientSideFirstName = payload.getString("modality_firstName");
        String clientSideLastName  = payload.getString("modality_lastName");
        String clientSideEmail     = payload.getString("modality_email");
        String clientSidePhone     = payload.getString("modality_phone");
        String clientSideAddress   = payload.getString("modality_address");
        String clientSideCity      = payload.getString("modality_city");
        String clientSideState     = payload.getString("modality_state");
        String clientSideZipCode   = payload.getString("modality_zipCode");
        String clientCountry       = payload.getString("modality_country");

        // Passing all the above data using the Authorize.net API to request a payment completion

        Environment environment = live ? Environment.PRODUCTION : Environment.SANDBOX;

        MerchantAuthenticationType merchantAuthentication = new MerchantAuthenticationType();
        merchantAuthentication.setName(apiLoginID);
        merchantAuthentication.setTransactionKey(apiTransactionKey);

        CustomerAddressType billingAddress = new CustomerAddressType();
        billingAddress.setFirstName(  clientSideFirstName != null ? clientSideFirstName : serverSideCustomer.firstName());
        billingAddress.setLastName(   clientSideLastName  != null ? clientSideLastName  : serverSideCustomer.lastName());
        billingAddress.setEmail(      clientSideEmail     != null ? clientSideEmail     : serverSideCustomer.email());
        billingAddress.setPhoneNumber(clientSidePhone     != null ? clientSidePhone     : serverSideCustomer.phone());
        billingAddress.setAddress(    clientSideAddress   != null ? clientSideAddress   : serverSideCustomer.address());
        billingAddress.setCity(       clientSideCity      != null ? clientSideCity      : serverSideCustomer.city());
        billingAddress.setState(      clientSideState     != null ? clientSideState     : serverSideCustomer.state());
        billingAddress.setZip(        clientSideZipCode   != null ? clientSideZipCode   : serverSideCustomer.zipCode());
        billingAddress.setCountry(    clientCountry       != null ? clientCountry       : serverSideCustomer.country());

        LineItemType anetItem = new LineItemType();
        anetItem.setItemId(serverItem.id());
        anetItem.setName(serverItem.name());
        anetItem.setDescription(serverItem.description());
        anetItem.setQuantity(BigDecimal.valueOf(serverItem.quantity()));
        anetItem.setUnitPrice(BigDecimal.valueOf(0.01 * serverItem.price())); // the modality amount is in cents

        ArrayOfLineItem lineItems = new ArrayOfLineItem();
        lineItems.getLineItem().add(anetItem);

        CustomerDataType customerData = new CustomerDataType();
        customerData.setId(serverSideCustomer.id());
        customerData.setEmail(serverSideCustomer.email());
        customerData.setType(CustomerTypeEnum.INDIVIDUAL);

        OpaqueDataType opaqueData = new OpaqueDataType();
        opaqueData.setDataDescriptor(dataDescriptor);
        opaqueData.setDataValue(dataValue);

        PaymentType paymentType = new PaymentType();
        paymentType.setOpaqueData(opaqueData);

        TransactionRequestType txnRequest = new TransactionRequestType();
        txnRequest.setTransactionType(TransactionTypeEnum.AUTH_CAPTURE_TRANSACTION.value());
        txnRequest.setAmount(BigDecimal.valueOf(0.01 * amount)); // the modality amount is in cents
        txnRequest.setPayment(paymentType);
        txnRequest.setBillTo(billingAddress);
        txnRequest.setCustomer(customerData);
        txnRequest.setLineItems(lineItems);

        CreateTransactionRequest request = new CreateTransactionRequest();
        request.setMerchantAuthentication(merchantAuthentication);
        request.setTransactionRequest(txnRequest);

        CreateTransactionController controller = new CreateTransactionController(request);
        controller.execute(environment);
        CreateTransactionResponse response = controller.getApiResponse();

        MessageTypeEnum resultCode = response == null ? null : response.getMessages().getResultCode();
        if (resultCode == MessageTypeEnum.OK) { // API request succeeded (doesn't mean the payment is successful)
            TransactionResponse transactionResponse = response.getTransactionResponse();
            String transId = transactionResponse.getTransId();
            String responseCode = transactionResponse.getResponseCode();
            PaymentStatus paymentStatus = "1".equals(responseCode) ? PaymentStatus.COMPLETED :  PaymentStatus.FAILED;
            return Future.succeededFuture(new GatewayCompletePaymentResult(
                null,
                transId,
                responseCode,
                paymentStatus
            ));
        } else { // API request failed (technical error)
            ANetApiResponse errorResponse = controller.getErrorResponse();
            MessagesType messages;
            if (errorResponse != null) {
                messages = errorResponse.getMessages();
            } else if (response != null)
                messages = response.getMessages();
            else
                messages = null;
            MessagesType.Message message = messages == null ? null : Collections.first(messages.getMessage());
            return Future.failedFuture("Authorize payment completion failed: " + (message == null ? "no response or no message" : message.getText() + " - code = " + message.getCode()));
        }
    }


    public Future<GatewayMakeApiPaymentResult> makeApiPayment(GatewayMakeApiPaymentArgument argument) {
        return Future.failedFuture("makeApiPayment() not yet implemented for Authorize.net");
    }

}
