// File generated by WebFX (DO NOT EDIT MANUALLY)

module mongoose.ecommerce.client.bookingprocess {

    // Direct dependencies modules
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.base.client.activity;
    requires mongoose.base.client.aggregates;
    requires mongoose.base.shared.entities;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.client.util;
    requires webfx.framework.shared.orm.datasourcemodelservice;
    requires webfx.kit.util;
    requires webfx.platform.client.windowhistory;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.ecommerce.client.activity.bookingprocess;

}