// File generated by WebFX (DO NOT EDIT MANUALLY)

module mongoose.crm.backoffice.bookingdetailspanel {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.base.backoffice.masterslave;
    requires mongoose.base.backoffice.operations.generic;
    requires mongoose.base.client.presentationmodel;
    requires mongoose.base.shared.entities;
    requires mongoose.crm.backoffice.operations.mail;
    requires mongoose.ecommerce.backoffice.operations.document;
    requires mongoose.ecommerce.backoffice.operations.documentline;
    requires mongoose.ecommerce.backoffice.operations.moneytransfer;
    requires webfx.extras.imagestore;
    requires webfx.extras.label;
    requires webfx.extras.visual.controls.grid;
    requires webfx.framework.client.action;
    requires webfx.framework.client.activity;
    requires webfx.framework.client.controls;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.operationaction;
    requires webfx.framework.client.orm.reactive.visual;
    requires webfx.framework.shared.orm.domainmodel;
    requires webfx.framework.shared.orm.entity;
    requires webfx.kit.util;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.crm.backoffice.controls.bookingdetailspanel;

}