name: Discover Vulnerabilities Using CodeQL

on: [push]

jobs:
  CodeQL-Build:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript,java

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19

      - name: Build with Maven
        run: mvn package -B -P 'vertx-fatjar,gwt-compile'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
