name: Enforce Google Java Style Guidelines

on: [push]

jobs:
  Google-Java-Format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "-n --set-exit-if-changed"
